version: "3.4"

services:
  backend:
    container_name: ${APP_NAME}-wordpress
    restart: always
    working_dir: /var/www/app
    tty: true
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./src/public/wp-content/uploads:/var/www/app/public/wp-content/uploads
    extra_hosts:
      - "dockerhost:${LOCAL_IP}"
    environment:
      CONTAINER_ROLE: fpm
      WEB_DOCUMENT_ROOT: /var/www/app/public
      WEB_PHP_TIMEOUT: 3000
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_POST_MAX_SIZE: 64M
      PHP_MAX_EXECUTION_TIME: 18000dc
      php.short_open_tag: "on"
