<?php
/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */
require_once dirname(__DIR__) . '/vendor/autoload.php';

/**
 * Use Dotenv to set required environment variables and load .env file in root
 */
(Dotenv\Dotenv::create(dirname(__DIR__))->safeLoad());

/**
 * Load Sentry
 */
if (!defined('SENTRY_LOADED') && getenv('SENTRY_DSN')) {
    Sentry\init([
        'dsn' => getenv('SENTRY_DSN'),
        'environment' => getenv('WP_ENV') ?: 'development',
    ]);
}

require_once dirname(__DIR__) . '/core/helpers.php';
require_once dirname(__DIR__) . '/core/bootstrap.php';
require_once dirname(__DIR__) . '/config/application.php';
require_once ABSPATH . 'wp-settings.php';
